### ISSUE TITLE
Unable to add maps from linked layers

### ISSUE THREAD

**Issue by gpetit** [orbisgis/orbisgis-plugin_mapcomposer#16]
If there is linked layers (i.e a shp linked in the Geocatalog), in the TOC, it's impossible to insert a map block.
OrbisGIS returns this error message :
```
ERROR [AWT-EventQueue-0] (Layer.java:157) - Cannot compute layer envelope:
The table "" does not contain a Geometry field, then the extent cannot be computed
```

Note that the TOC has been saved before opening the map composer.

@nicolas-f  maybe an idea ? A bug linked to the detection of the geometry type with linked tables ?

In this case, the OWS-C Panel is like this :
![panel](https://cloud.githubusercontent.com/assets/1871248/5072025/db740648-6e76-11e4-948f-637e286ff88e.png)

**Comment by gpetit** [comment]
I tried again, and this problem is still there.

```
Unable to load the data source uri file:/home/Documents/SIG/Data/IGN%2520-%2520GeoFLA%2520Communes/GEOFLA_1-1_SHP_LAMB93_FR-ED111/DEPARTEMENTS/DEPARTEMENT.shp.
Cannot draw  the table does not exists
Cannot compute layer envelope:
The table "" does not contain a Geometry field, then the extent cannot be computed
```

**Comment by ebocher** [comment]
It works so I close it
