### ISSUE TITLE
Check for compatibility

### ISSUE THREAD

**Issue by nicolas-f** [orbisgis/orbisgis-plugin_mapcomposer#45]
Check the compatibility of this plugin with the last version of OrbisGIS.

**Comment by nicolas-f** [comment]
@ebocher @SPalominos I can't deploy this plug-in.

**Comment by ebocher** [comment]
Do you have a message an error ?

**Comment by nicolas-f** [comment]
Bundle cannot be resolved. Version/Package requirement issues. I think some orbisgis java packages has been moved since.

**Comment by SPalominos** [comment]
Do you have any output message from OrbisGIS or from a console/terminal? Otherwise, I can't reproduce the bug with the last OrbisGIS version (5.1.0-SNAPSHOT-2017-01-03) under linux with a fresh workspace. With which version of OrbisGIS are you experiencing the bug under which operating system ?

**Comment by nicolas-f** [comment]
Oups, sorry for the trouble, it was a proxy error.

```Resolver: Install error - org.orbisgis.map-composer```
